apartrevenge/urls.py
from django.contrib import admin
from django.urls import path, include
from aptrent.views import handler403

handler403 = 'aptrent.views.handler403'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aptrent.urls'))
]

aptrent/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .decorators import check_user_type
from .views import (
    registro, 
    index, 
    custom_login, 
    custom_logout, 
    arrendadores_view, 
    arrendatarios_view, 
    editar_perfil,
    agregar_inmueble, 
    editar_inmueble, 
    eliminar_inmueble, 
    lista_inmuebles,
    crear_solicitud_arriendo,
    listar_solicitudes,
    eliminar_solicitud

)

urlpatterns = [
    
    # URLS para gestion de usuairio
    path('registro/', registro, name='registro'),
    path('login/', custom_login, name='login'),
    path('logout/', custom_logout, name='logout'),    
    path('perfil/', editar_perfil, name='perfil'),
    
    # Path arrendadores
    path('arrendadores/', check_user_type('arrendador')(arrendadores_view), name='arrendadores'),
    path('inmuebles/agregar/', check_user_type('arrendador')(agregar_inmueble), name='agregar_inmueble'),
    path('inmuebles/editar/<int:id>/', check_user_type('arrendador')(editar_inmueble), name='editar_inmueble'),
    path('inmuebles/eliminar/<int:id>/', check_user_type('arrendador')(eliminar_inmueble), name='eliminar_inmueble'),

    # Path Arremdatarios
    path('arrendatarios/', check_user_type('arrendatario')(arrendatarios_view), name='arrendatarios'),
    path('solicitudes/', listar_solicitudes, name='listar_solicitudes'),
    path('solicitudes/crear/<int:inmueble_id>/', crear_solicitud_arriendo, name='crear_solicitud_arriendo'),  
    path('solicitudes/eliminar/<int:solicitud_id>/', eliminar_solicitud, name='eliminar_solicitud'),


    # Public Pages
    path('', index, name='index'),
    path('inmuebles/', lista_inmuebles, name='lista_inmuebles'),

]

aptrent/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


# Apartado de Usuarios
class UserProfile(models.Model):
    USER_TYPE_CHOICES = (
        ('arrendatario', 'Arrendatario'),
        ('arrendador', 'Arrendador'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)  # Relación uno a uno con User
    rut = models.CharField(max_length=12, unique=True)  # RUT único
    telefono = models.CharField(max_length=9, blank=True)  # Teléfono (opcional)
    user_type = models.CharField(max_length=20, choices=USER_TYPE_CHOICES)  # Tipo de usuario
    direccion = models.CharField(max_length=200, blank=True)  # Dirección (opcional)
  
    def __str__(self):
        return self.user.username  # Devuelve el nombre de usuario como representación
    

# Gestor Comunas y Regiones
class Region(models.Model):
    numero_romano = models.CharField(max_length=10, unique=True)  # Ejemplo: "XIII"
    nombre = models.CharField(max_length=100, unique=True)       # Ejemplo: "Metropolitana de Santiago"

    def __str__(self):
        return f"{self.numero_romano} - {self.nombre}"

class Comuna(models.Model):
    nombre = models.CharField(max_length=100)       # Ejemplo: "Providencia"
    region = models.ForeignKey('Region', on_delete=models.CASCADE)  # Relación con Region

    def __str__(self):
        return f"{self.nombre} ({self.region})"
    

# Inmuebles
class Inmueble(models.Model):
    # Mejor dejarlo limitado por un Choice para evitar mal tipado
    TIPO_INMUEBLE_CHOICES = (
        ('casa', 'Casa'),
        ('departamento', 'Departamento'),
        ('oficina', 'Oficina'),
    )
    
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField()
    m2_construidos = models.FloatField()
    m2_totales = models.FloatField()
    estacionamientos = models.IntegerField()
    habitaciones = models.IntegerField()
    banos = models.IntegerField()
    direccion = models.CharField(max_length=200)
    comuna = models.ForeignKey('Comuna', on_delete=models.CASCADE, blank=True, null=True)  # Relación con Comuna
    region = models.ForeignKey('Region', on_delete=models.CASCADE, blank=True, null=True)  # Relación con Region
    tipo_inmueble = models.CharField(max_length=50, choices=TIPO_INMUEBLE_CHOICES)
    precio_mensual = models.DecimalField(max_digits=10, decimal_places=2)
    propietario = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    
    def __str__(self):
        return self.nombre
    

# Asignacion de inmueble
class SolicitudArriendo(models.Model):
    id_solicitud = models.AutoField(primary_key=True)
    
    # Relación con el modelo User
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    inmueble = models.ForeignKey('Inmueble', on_delete=models.CASCADE)
    fecha_solicitud = models.DateField()
    estado_solicitud = models.CharField(max_length=20, choices=[
        ('pendiente', 'Pendiente'),
        ('aceptada', 'Aceptada'),
        ('rechazada', 'Rechazada')
    ], default='pendiente')  # Valor por defecto 'pendiente'
    
    def __str__(self):
        return f"Solicitud {self.id_solicitud} - {self.user.first_name} {self.user.last_name}"

aptrent/forms.py
from django import forms
from django.forms import TextInput, EmailInput, PasswordInput, Select
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile, Inmueble, SolicitudArriendo

class CustomUserCreationForm(UserCreationForm):
    # Campos adicionales de UserProfile
    rut = forms.CharField(max_length=12, required=True, label="RUT")
    telefono = forms.CharField(max_length=15, required=True, label="Teléfono")
    user_type = forms.ChoiceField(choices=UserProfile.USER_TYPE_CHOICES, required=True, label="Tipo de Usuario")
    direccion = forms.CharField(max_length=255, required=True, label="Dirección")
    
    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email')  # Incluye los campos de User

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()

        # Crear UserProfile solo si no existe
        UserProfile.objects.update_or_create(
            user=user,
            defaults={
                'rut': self.cleaned_data['rut'],
                'telefono': self.cleaned_data['telefono'],
                'user_type': self.cleaned_data['user_type'],
                'direccion': self.cleaned_data['direccion']
            }
        )

        return user
    

class InmuebleForm(forms.ModelForm):
    class Meta:
        model = Inmueble
        fields = ['nombre', 'descripcion', 'm2_construidos', 'm2_totales', 'estacionamientos',
                  'habitaciones', 'banos', 'direccion', 'comuna', 'region', 'tipo_inmueble', 'precio_mensual']
        widgets = {
            'descripcion': forms.Textarea(attrs={'rows': 4}),
            'tipo_inmueble': forms.Select(choices=Inmueble.TIPO_INMUEBLE_CHOICES),
        }

class SolicitudArriendoForm(forms.ModelForm):
    class Meta:
        model = SolicitudArriendo
        fields = ['inmueble', 'fecha_solicitud']
        widgets = {
            'fecha_solicitud': forms.DateInput(attrs={'type': 'date'}),
        }
        labels = {
            'inmueble': 'Seleccione el inmueble',
            'fecha_solicitud': 'Fecha de la solicitud',
        }

aptrent/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import PermissionDenied
from django.db.models import Exists, OuterRef
from .decorators import check_user_type
from .forms import CustomUserCreationForm, InmuebleForm, SolicitudArriendoForm
from .models import UserProfile, Inmueble, SolicitudArriendo

# Mantenedor de otras Paginas
def index(request):
    inmuebles = Inmueble.objects.filter(comuna__isnull=False, region__isnull=False)
    
    # Login
    if request.method == 'POST':
        formlog = AuthenticationForm(request, data=request.POST)
        if formlog.is_valid():
            user = formlog.get_user()
            login(request, user)
            # Redirigir según el tipo de usuario
            user_profile = user.userprofile  # Accede al perfil del usuario
            if user_profile.user_type == 'arrendatario':
                return redirect('arrendatarios')  # Redirige a la vista de arrendatarios
            elif user_profile.user_type == 'arrendador':
                return redirect('arrendadores')  # Redirige a la vista de arrendadores
            return redirect('index')  # Redirige al home si no tiene tipo
    else:
        formlog = AuthenticationForm()
    
    # Registrer
    if request.method == 'POST':
        formreg = CustomUserCreationForm(request.POST)
        if formreg.is_valid():
            formreg.save()
            # Inicia sesión automáticamente después de registrarse
            user = formreg.save()
            login(request, user)
            # Redirige a la página principal o cualquier otra página
            return redirect('index')  # Cambia a la URL que desees
    else:
        formreg = CustomUserCreationForm()
    
    return render(request, 'aptrent/index.html', {
            'inmuebles': inmuebles,
            'formlog': formlog,
            'formreg': formreg
        }       
    )


@login_required
@check_user_type('arrendador')
def arrendadores_view(request):
    user = request.user
    inmuebles = Inmueble.objects.filter(propietario=user)
    return render(request, 'aptrent/arrendadores.html', {'inmuebles': inmuebles})

@login_required
@check_user_type('arrendatario')
def arrendatarios_view(request):
    # Excluir inmuebles con solicitudes pendientes
    inmuebles_con_solicitudes = SolicitudArriendo.objects.filter(
        inmueble=OuterRef('pk'),
        estado_solicitud='pendiente'
    )
    
    inmuebles = Inmueble.objects.filter(
        comuna__isnull=False, 
        region__isnull=False
    ).annotate(
        tiene_solicitud_pendiente=Exists(inmuebles_con_solicitudes)
    ).filter(
        tiene_solicitud_pendiente=False
    )
    
    return render(request, 'aptrent/arrendatarios.html', {'inmuebles': inmuebles})

def handler403(request, exception):
    messages.error(request, "No tienes permiso para acceder a esta página.")
    return redirect('index')



# Mantenedor Usuarios
def registro(request):
    if request.method == 'POST':
        formreg = CustomUserCreationForm(request.POST)
        if formreg.is_valid():
            formreg.save()
            # Inicia sesión automáticamente después de registrarse
            user = formreg.save()
            login(request, user)
            # Redirige a la página principal o cualquier otra página
            return redirect('index')  # Cambia a la URL que desees
    else:
        formreg = CustomUserCreationForm()
    return render(request, 'aptrent/registro.html', {'form': formreg})

def custom_logout(request):
    # Cerrar sesión
    logout(request)
    return redirect('index')

def custom_login(request):
    if request.method == 'POST':
        formlog = AuthenticationForm(request, data=request.POST)
        if formlog.is_valid():
            user = formlog.get_user()
            login(request, user)
            # Redirigir según el tipo de usuario
            user_profile = user.userprofile  # Accede al perfil del usuario
            if user_profile.user_type == 'arrendatario':
                return redirect('arrendatarios')  # Redirige a la vista de arrendatarios
            elif user_profile.user_type == 'arrendador':
                return redirect('arrendadores')  # Redirige a la vista de arrendadores
            return redirect('index')  # Redirige al home si no tiene tipo
    else:
        formlog = AuthenticationForm()
    return render(request, 'registration/login.html', {'form': formlog})
    

@login_required
def editar_perfil(request):
    if request.method == 'POST':
        # Obtener datos del formulario
        email = request.POST.get('email')
        telefono = request.POST.get('telefono')
        direccion = request.POST.get('direccion')

        # Actualizar datos del usuario
        request.user.email = email
        request.user.save()

        # Actualizar datos del perfil
        user_profile = UserProfile.objects.get(user=request.user)
        user_profile.telefono = telefono
        user_profile.direccion = direccion
        user_profile.save()

        messages.success(request, "Tu perfil ha sido actualizado correctamente.")
        return redirect('perfil')

    return render(request, 'aptrent/perfil.html')



# Mantenedor Inmueble
@login_required
def agregar_inmueble(request):    
    if request.method == 'POST':
        form = InmuebleForm(request.POST)
        if form.is_valid():
            inmueble = form.save(commit=False)
            inmueble.propietario = request.user
            inmueble.save()
            messages.success(request, 'Inmueble agregado con éxito.')
            return redirect('arrendadores')
    else:
        form = InmuebleForm()

    return render(request, 'aptrent/inmuebles/agregar_inmueble.html', {'form': form})

@login_required
def editar_inmueble(request, id):
    inmueble = get_object_or_404(Inmueble, id=id, propietario=request.user)  # Solo el propietario puede editar
    if request.method == 'POST':
        form = InmuebleForm(request.POST, instance=inmueble)
        if form.is_valid():
            form.save()
            messages.success(request, 'Inmueble actualizado con éxito.')
            return redirect('arrendadores')
    else:
        form = InmuebleForm(instance=inmueble)

    return render(request, 'aptrent/inmuebles/editar_inmueble.html', {'form': form})

def lista_inmuebles(request):
    user = request.user

    if user.is_authenticated:
        user_profile = UserProfile.objects.get(user=user)
        if user_profile.user_type == 'arrendador':
            inmuebles = Inmueble.objects.filter(propietario=user, comuna__isnull=False, region__isnull=False)
        else:
            inmuebles = Inmueble.objects.filter(comuna__isnull=False, region__isnull=False)
    else:
        # Para usuarios no autenticados, muestra todos los inmuebles disponibles
        print("Usuario no autenticado.")
        inmuebles = Inmueble.objects.filter(comuna__isnull=False, region__isnull=False)

    return render(request, 'aptrent/inmuebles/lista_inmuebles_publica.html', {'inmuebles': inmuebles})

@login_required
def eliminar_inmueble(request, id):
    inmueble = get_object_or_404(Inmueble, id=id)

    # Verificar que el usuario sea el propietario
    if inmueble.propietario != request.user:
        return PermissionDenied("No tienes permiso para eliminar este inmueble.")
    
    if request.method == 'POST':
        inmueble.delete()
        return redirect('arrendadores')
    
    return render(request, 'aptrent/inmuebles/eliminar_inmueble.html', {'inmueble': inmueble})



# Mantenedor Solicitudes
@login_required
def crear_solicitud_arriendo(request, inmueble_id):
    # Verificar que el usuario es arrendatario
    user_profile = get_object_or_404(UserProfile, user=request.user)
    if user_profile.user_type != 'arrendatario':
        return redirect('index')

    # Obtener el inmueble por ID
    inmueble = get_object_or_404(Inmueble, id=inmueble_id)

    if request.method == 'POST':
        form = SolicitudArriendoForm(request.POST)
        if form.is_valid():
            solicitud = form.save(commit=False)
            solicitud.user = request.user
            solicitud.inmueble = inmueble
            solicitud.save()
            return redirect('arrendatarios')  # Redirigir a la lista después de guardar
    else:
        form = SolicitudArriendoForm(initial={'inmueble': inmueble})

    return render(request, 'aptrent/solicitudes/crear_solicitud.html', {'form': form, 'inmueble': inmueble})

@login_required
def listar_solicitudes(request):
    # Filtrar solicitudes realizadas por el usuario autenticado
    solicitudes = SolicitudArriendo.objects.filter(user=request.user).select_related('inmueble')
    return render(request, 'aptrent/solicitudes/listar_solicitudes.html', {'solicitudes': solicitudes})

@login_required
def eliminar_solicitud(request, solicitud_id):
    solicitud = get_object_or_404(SolicitudArriendo, id_solicitud=solicitud_id, user=request.user)
    
    if request.method == 'POST':
        solicitud.delete()
        messages.success(request, 'La solicitud ha sido eliminada con éxito.')
        return redirect('arrendatarios')  # Reemplaza con el nombre de tu vista de "Mis solicitudes"
    
    return render(request, 'aptrent/solicitudes/confirmar_eliminar.html', {'solicitud': solicitud})

aptrent/templates/aptrent/inmuebles/agregar_inmueble.html
{% extends 'aptrent/layout/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container my-5">
        <!-- Mensajes -->
        {% if messages %}
            <div class="alert alert-info">
                <ul class="mb-0">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        
        <!-- Título del Formulario -->
        <h2 class="mb-4 text-center">Agregar nuevo inmueble</h2>
        
        <!-- Formulario -->
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            
            <!-- Botón de Guardar -->
            <div class="text-center mt-4">
                <button type="submit" class="btn btn-primary">Guardar</button>
                <a class="btn btn-secondary" href="{% url 'arrendadores' %}">Vovler</a>
            </div>
        </form>
    </div>
{% endblock %}

aptrent/templates/aptrent/inmuebles/editar_inmueble.html
{% extends 'aptrent/layout/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container my-5">
        <!-- Título del Formulario -->
        <h2 class="mb-4 text-center">Editar Inmueble</h2>

        <!-- Formulario -->
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}

            <!-- Botón de Guardar -->
            <div class="text-center mt-4">
                <button type="submit" class="btn btn-primary">Guardar cambios</button>
                <a class="btn btn-secondary" href="{% url 'arrendadores' %}">Vovler</a>
            </div>
        </form>
    </div>
{% endblock %}

aptrent/templates/aptrent/inmuebles/eliminar_inmueble.html
{% block content %}
<h2>Confirmar eliminación</h2>
<p>¿Estás seguro de que deseas eliminar la propiedad "{{ inmueble.nombre }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Sí, eliminar</button>
    <a href="{% url 'arrendadores' %}">Cancelar</a>
</form>
{% endblock %}

aptrent/templates/aptrent/inmuebles/lista_inmuebles.html
{% load static %}

{% block content %}
    {% if user.userprofile.user_type == 'arrendador' %}
    <div class="container w-90 my-5">
        <h2 class="text-center display-4 fw-bold mb-4">Inmuebles creados</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Precio Mensual</th>
                    <th>Tipo</th>
                    <th>Comuna</th>
                    <th>Región</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for inmueble in inmuebles %}
                <tr>
                    <td>{{ inmueble.nombre }}</td>
                    <td>{{ inmueble.descripcion }}</td>
                    <td>{{ inmueble.precio_mensual }} CLP</td>
                    <td>{{ inmueble.get_tipo_inmueble_display }}</td>
                    <td>{{ inmueble.comuna }}</td>
                    <td>{{ inmueble.region }}</td>
                    <td>
                        <a href="{% url 'editar_inmueble' inmueble.id %}" class="btn btn-warning btn-sm">Editar</a>
                        <button class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal-{{ inmueble.id }}">
                            Eliminar
                        </button>
                    </td>
                </tr>

                <!-- Modal de Confirmación -->
                <div class="modal fade" id="deleteModal-{{ inmueble.id }}" tabindex="-1" aria-labelledby="deleteModalLabel-{{ inmueble.id }}" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel-{{ inmueble.id }}">Confirmar eliminación</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <p>¿Estás seguro de que deseas eliminar la propiedad "{{ inmueble.nombre }}"?</p>
                            </div>
                            <div class="modal-footer">
                                <form method="post" action="{% url 'eliminar_inmueble' inmueble.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">
                                        <i class="bi bi-check-circle">Si, Eliminar</i>
                                    </button>
                                </form>
                                <button type="button" class="btn btn-outline-danger ms-2" data-bs-dismiss="modal">
                                    <i class="bi bi-check-circle">No, Vovler</i><!-- Ícono -->
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                {% empty %}
                <tr>
                    <td colspan="7" class="text-center">No hay inmuebles disponibles.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% elif user.userprofile.user_type == 'arrendatario' %}
    
    <div class="container w-90 my-5">
        <h2 class="display-3 text-center fw-bold my-3">Mira Nuestro Catálogo Disponible</h2>
        
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for inmueble in inmuebles %}
            <div class="col">
                <div class="card">
                    <div class="card-image">
                        {% if inmueble.tipo_inmueble == 'casa' %}
                            <img src="{% static 'images/casa.webp' %}" alt="Imagen de {{ inmueble.tipo_inmueble }}" class="card-img-top">
                        {% elif inmueble.tipo_inmueble == 'departamento' %}
                            <img src="{% static 'images/departamento.webp' %}" alt="Imagen de {{ inmueble.tipo_inmueble }}" class="card-img-top">
                        {% elif inmueble.tipo_inmueble == 'oficina' %}
                            <img src="{% static 'images/oficina.webp' %}" alt="Imagen de {{ inmueble.tipo_inmueble }}" class="card-img-top">
                        {% else %}
                            <img src="https://via.placeholder.com/300x200" alt="Sin Imagen" class="card-img-top">
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ inmueble.nombre }}</h5>
                        <p class="card-text">{{ inmueble.descripcion|truncatewords:20 }}</p>
                        <ul class="list-unstyled">
                            <li><strong>Precio Mensual:</strong> {{ inmueble.precio_mensual }} CLP</li>
                            <li><strong>Tipo:</strong> {{ inmueble.get_tipo_inmueble_display }}</li>
                            <li><strong>Comuna:</strong> {{ inmueble.comuna }}</li>
                            <li><strong>Región:</strong> {{ inmueble.region }}</li>
                        </ul>
                    </div>
                    <div class="card-footer text-center">
                        <a href="{% url 'crear_solicitud_arriendo' inmueble.id %}" class="btn btn-success w-100">Solicitar Arriendo</a>
                    </div>
                </div>
            </div>
            {% empty %}
            <p>No hay inmuebles disponibles.</p>
            {% endfor %}
        </div>
    </div>

    {% endif %}
{% endblock %}

aptrent/templates/aptrent/inmuebles/lista_inmuebles_publica.html
{% load static %}

{% block content %}
<div class="container w-90 my-5">
<h2 class="display-3 text-center fw-bold my-3">Mira nuestro Catálogo Disponible</h2>

<div class="card-container ">
    {% for inmueble in inmuebles %}
    <div class="card">
        <div class="card-image">
            {% if inmueble.tipo_inmueble == 'casa' %}
                <img src="{% static 'images/casa.webp' %}" alt="Imagen de {{ inmueble.tipo_inmueble }}">
            {% elif inmueble.tipo_inmueble == 'departamento' %}
                <img src="{% static 'images/departamento.webp' %}" alt="Imagen de {{ inmueble.tipo_inmueble }}">
            {% elif inmueble.tipo_inmueble == 'oficina' %}
                <img src="{% static 'images/oficina.webp' %}" alt="Imagen de {{ inmueble.tipo_inmueble }}">
            {% else %}
                <img src="https://via.placeholder.com/300x200" alt="Sin Imagen">
            {% endif %}
        </div>
        <div class="card-content">
            <h3>{{ inmueble.nombre }}</h3>
            <p>{{ inmueble.descripcion|truncatewords:20 }}</p>
            <ul>
                <li><strong>Precio Mensual:</strong> {{ inmueble.precio_mensual }} CLP</li>
                <li><strong>Tipo:</strong> {{ inmueble.get_tipo_inmueble_display }}</li>
                <li><strong>Comuna:</strong> {{ inmueble.comuna }}</li>
                <li><strong>Región:</strong> {{ inmueble.region }}</li>
            </ul>
        </div>
    </div>
    {% empty %}
    <p>No hay inmuebles disponibles.</p>
    {% endfor %}
</div>
</div>
{% endblock %}